# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
 name: 'srinu-azure'  

steps:
- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1(98b63508-3949-41ff-8099-f1bd92405eb6)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    codeCoverageFailIfEmpty: true
    codeCoverageRestoreOriginalPomXml: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
