# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: srinu-agent

stages:
  - stage: maven-compile
    displayName: 'maven-compile'
    jobs:
      - job: maven_compile
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Free-Subscription(98b63508-3949-41ff-8099-f1bd92405eb6)'
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: maven-package
    displayName: 'maven-package'
    jobs:
      - job: maven_package
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Free-Subscription(98b63508-3949-41ff-8099-f1bd92405eb6)'
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: copy jar file
    displayName: 'Jar-file'
    jobs:
      - job: jar-file
        steps:
          - task: CopyFiles@2
            displayName: 'Copy .jar file'
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '/*.jar'
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()

  - stage: PublishBuildArtifact
    displayName: "PublishBuildArtifacts"
    jobs:
      - job: PublishBuildArtifacts
        steps:
            - task: PublishBuildArtifacts@1
              inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: 'drop'
               publishLocation: 'Container'

        

