apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: admin-user  # Replace with the actual user
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin-reader  # Replace with the desired ClusterRole
---