apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    app: ecommerce-application
spec:
  type: NodePort
  selector:
    app: ecommerce-application
  ports:
    - name: http
      protocol: TCP
      port: 80              # Port exposed inside the cluster
      targetPort: 1199      # Port your Spring Boot app listens on
      nodePort: 30080       # Optional: fixed external port (range 30000–32767)
---