apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app-labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 1199   # Port exposed inside the cluster
      targetPort: 1199      # Port your Spring Boot app listens on
  selector:
    app: {{- include "app-labels" . | nindent 4 }}
  type: {{ .Values.service.type }}     # Optional: fixed external port (range 30000–32767)
---