apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: mywebapp
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
      tier: {{ .Values.app.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}
        tier: {{ .Values.app.env }}
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: "{{ .Values.app.container.image }}:{{ .Values.app.container.tag }}"
          imagePullPolicy: {{ .Values.app.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"    # 50 milli cores (1/20 CPU)
            limits:
              memory: "128Mi" # 128 mebibytes
              cpu: "100m"
---