apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.appName }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.label }}
    env: {{ .Values.app.env }}
spec:
  ports:
    - port: 1199
      protocol: TCP
      name: flask
  selector:
    app: {{ .Values.service.label }}
    env: {{ .Values.app.env }}
  type: NodePort