apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-ecommerce-deployment
  namespace: spring
  labels:
    app: ecommerce-application
spec:
  replicas: 20
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ecommerce-application
  template:
    metadata:
      labels:
        app: ecommerce-application
    spec:
      containers:
        - name: application-server-container
          image: srinu641/spring-application-k8s:v1.04
          ImagePullPolicy: Always #IfNotPresent
          ports:
            - containerPort: 1199
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "250m"
      startupProbe:
        tcpSocket:
          port: 8181
        initialDelaySeconds: 20
        periodSeconds: 5
---
