apiVersion: v1
kind: Namespace
metadata:
  name: spring
  labels:
    name: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    monitoring: prometheus
    istio-injection: enabled
---