apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    app: ecommerce-application
    env: dev
spec:
  ports:
    - name: http
      port: 1199              # Port exposed inside the cluster
      targetPort: 1199      # Port your Spring Boot app listens on
  selector:
    app: ecommerce-application
  type: NodePort
---
#apiVersion: v1
##kind: Service
#metadata:
#  name: spring-boot-service
#  namespace: spring
#  labels:
#    app: ecommerce-application
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enable: "true"
#    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enable: "true"
#    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "30"
#spec:
#  ports:
#    - port: 1199
#      protocol: TCP
#      targetPort: 1199
#  selector:
#    app: ecommerce-application
#  type: LoadBalancer
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  selector:
#    app.kubernetes.io/name: proxy
#  ports:
#    - name: name-of-service-port
#      protocol: TCP
#      port: 1199
#      targetPort: http-web-sv
#---