apiVersion: v1
kind: Service
metadata:
  name: spring-ecommerce-application-svc
  namespace: spring
  labels:
    app: zomato-svc
spec:
  type: NodePort
  ports:
    - port: 1199
      targetPort: 1199
      nodePort: 30003
  selector:
    app: ecommerce-application
---