#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: webserver-cpu-hpa
#  namespace: spring
#spec:
#  maxReplicas: 10
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: ecommerce-application
#  targetCPUUtilizationPercentage: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: spring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commerce-application
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
